chore(android): deprecation warnings for splash screen
ionic-team/capacitor-plugins pull request #1012
Opened 2022-05-31 13:09 UTC by ItsChaceD

This PR fixes the deprecation warnings on Android for the Splash Screen plugin.

2022-07-21 18:05 UTC, giralte-ionic approved these changes

2022-07-21 21:14 UTC, IT-MikeS approved these changes

2022-07-22 13:10 UTC, jcesarmobile requested changes
Adding `"splashFullScreen": true` or `"splashImmersive": true` in the config file make apps crash on Android 12 when calling Show(); (maybe other versions too).

It's because it should be called on the UI thread.
Should be put inside 
```
activity.runOnUiThread(
            () -> {
            });
```
There is no activity on `buildViews` method, but there is line like this `Activity activity = (Activity) context;` that can be moved before of the if to use it.

Then `"splashImmersive": true` will still crash because the `splashImage` view is not on the window yet, the whole `if (config.isImmersive())` block should be moved after `windowManager.addView(splashImage, params);`.

In older Android versions it doesn't crash, but doesn't work neither, instead of removing the deprecated code, create new `legacyImmersive` and `legacyFullScreen` functions and use those on the Android versions where it wasn't deprecated. 

Same for `setLayerType`, keep the `setDrawingCacheEnabled` for the Android versions where it wasn't deprecated in a new function and use `setLayerType` where it's deprecated.

`"splashFullScreen": true` should hide the status bar
`"splashImmersive": true` should hide the status bar and the navigation buttons (test on a device or simulator that have software buttons for navigation)

2022-08-24 12:02 UTC, jcesarmobile requested changes
Added a few comments.
Also, when using `"splashFullScreen": true`, on Android 11+ the status bar is not hidden and it should.

2022-11-03 17:47 UTC, giralte-ionic approved these changes

2022-11-03 17:54 UTC, jcesarmobile approved these changes

2022-11-09 14:50 UTC, IT-MikeS approved these changes

2022-11-09 15:32 UTC, merged