fix(geolocation): reject checkPermissions / requestPermissions if location services are disabled
ionic-team/capacitor-plugins pull request #1053
Opened 2022-06-22 13:53 UTC by theproducer

This PR will check the Android location services and will throw an error in `checkPermissions` and `requestPermissions` if it's disabled, bringing the behavior inline with iOS.

closes: https://github.com/ionic-team/capacitor-plugins/issues/1035

2022-06-22 14:31 UTC, giralte-ionic approved these changes

2022-06-22 17:17 UTC, jcesarmobile requested changes
I think we should have a helper method in the implementation class that returns if location is available or not and use that instead of using the LocationManagerCompat class from the plugin class.
Will simplify the code and would be useful for users using the implementation class.

The implementation class already uses isLocationEnabled twice, so would be good if those calls could be replaced with the new helper method too.

2022-06-23 12:02 UTC, jcesarmobile commented on geolocation/android/src/main/java/com/capacitorjs/plugins/geolocation/GeolocationPlugin.java
> +            call.reject("System location services are not enabled");
```suggestion
            call.reject("Location services are not enabled");
```
Match the current iOS message

2022-06-23 12:03 UTC, jcesarmobile requested changes
just a minor comment about the error message, it should match the message used on iOS.

2022-06-23 21:09 UTC, jcesarmobile approved these changes

2022-06-24 13:16 UTC, merged

2023-01-05 20:32 UTC, tigohenryschultz commented
Location requests are no longer working on Android 31, I wonder if this has anything to do with it:  https://github.com/ionic-team/capacitor-plugins/issues/1363