feat(google-maps): Marker Customization Options
ionic-team/capacitor-plugins pull request #1146
Opened 2022-08-24 21:09 UTC by theproducer

2022-09-01 16:39 UTC, ItsChaceD requested changes

2022-09-01 16:39 UTC, ItsChaceD commented on google-maps/e2e-tests/android/app/build.gradle
> -plugins {
Was this supposed to be removed? Without it the Android app will throw a manifest error.

2022-09-01 16:39 UTC, ItsChaceD commented on google-maps/e2e-tests/android/app/build.gradle
> -def getApiKey() {
This is also a part of the secrets gradle plugin

2022-09-01 16:39 UTC, ItsChaceD commented on google-maps/e2e-tests/android/app/build.gradle
> -        manifestPlaceholders = [MAPS_API_KEY:"${getApiKey()}"]
Also a part of secrets plugin

2022-09-01 16:39 UTC, ItsChaceD commented on google-maps/e2e-tests/android/build.gradle
> -        classpath "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:2.0.0"
Need this for setting `MAPS_API_KEY`

2022-09-01 16:39 UTC, ItsChaceD commented on google-maps/e2e-tests/src/pages/Markers/MarkerCustomizations.tsx
> +  const removeAllMarkers = async () => {
This only removes the last markers added, not all on the map. Not sure if it's necessary to fix, but would help being able to test all functions at once

2022-09-06 18:58 UTC, IT-MikeS approved these changes

2022-09-07 15:49 UTC, ItsChaceD approved these changes

2022-09-12 13:55 UTC, merged