Fix bug in SDK 33 where opening the gallery when taking a picture fails due to permissions
ionic-team/capacitor-plugins pull request #1331
Opened 2022-12-14 17:11 UTC by modus-jose

2023-03-09 06:53 UTC, ItsChaceD approved these changes

2023-03-09 15:37 UTC, jcesarmobile requested changes
the alias should be a simpler string, maybe call it `media`?

The new alias should be added to the types so it can be requested independently
https://github.com/ionic-team/capacitor-plugins/blob/main/camera/src/definitions.ts#L5-L10

And also should be documented in the README

2023-07-28 18:11 UTC, markemer commented
Address @jcesarmobile's comments and conflicts and this should be gtg.

2023-07-28 23:26 UTC, jcesarmobile commented
This was addressed by the linked PR from chace

2023-07-28 23:26 UTC, closed without merging