chore(google-maps)(android): update maps dependencies
ionic-team/capacitor-plugins pull request #1449
Opened 2023-03-03 00:03 UTC by ItsChaceD

Update the Google Maps Utils dependencies for the `google-maps` plugin

2023-03-07 14:28 UTC, jcesarmobile approved these changes

2023-03-08 16:26 UTC, theproducer requested changes
Looks like the Google Maps Utils version is a major version change, and with it are some changes to the `ClusterItem` interface that we need to fix in `CapacitorGoogleMapMarker`.

2023-03-09 16:51 UTC, ItsChaceD commented
> Looks like the Google Maps Utils version is a major version change, and with it are some changes to the `ClusterItem` interface that we need to fix in `CapacitorGoogleMapMarker`.

We will have to review/merge #1474to fix this

2023-03-09 16:51 UTC, ItsChaceD commented
> changes look good, but looks like something broke with the change, so we should create a new issue about it first and fix it (if can be fixed without making the dependency update first)

We will have to review/merge #1474 to fix this

2023-03-14 20:31 UTC, markemer approved these changes

2023-03-15 15:30 UTC, merged