chore(camera): update docs to show web only supports png/gif
ionic-team/capacitor-plugins pull request #1524
Opened 2023-04-05 15:44 UTC by ItsChaceD

This PR clarifies that the web only supports `png` or `gif` and not `jpeg` files.
See #1148

2023-04-05 17:15 UTC, giralte-ionic approved these changes

2023-04-10 15:49 UTC, IT-MikeS approved these changes

2023-04-14 14:44 UTC, jcesarmobile requested changes
I've been testing and looks like I was wrong on my comment or things have changed since then, but I'm getting jpeg on chrome, while on safari and firefox I get png. 

So maybe mention that the format is dependent on the browser used?

2023-04-14 14:44 UTC, jcesarmobile commented on camera/src/definitions.ts
> +   * The quality of image to return, from 0-100
quality is only supported on android and ios, where it's always jpeg, so no need to delete it, but maybe add a note about it not being supported on web.

2023-04-26 16:06 UTC, jcesarmobile requested changes
For format, where it says "Web supports jpeg and png", it should also mention that depends on the browser.

2023-05-03 10:42 UTC, jcesarmobile approved these changes

2023-05-03 11:11 UTC, merged