chore(browser): Update default androidxBrowserVersion value
ionic-team/capacitor-plugins pull request #1903
Opened 2023-11-15 16:49 UTC by jcesarmobile

2023-11-15 17:53 UTC, giralte-ionic approved these changes

2023-11-15 18:49 UTC, ItsChaceD requested changes
Version `1.7.0` was released today

2023-11-15 18:55 UTC, jcesarmobile commented
Interesting, I see the release notes but I don't see the release available on maven central or google repositories.
Will wait until it appears there to update.

2023-11-20 14:38 UTC, IT-MikeS approved these changes

2023-11-20 15:00 UTC, merged