fix(keyboard): Setting keyboard style during onKeyboardWillHide
ionic-team/capacitor-plugins pull request #1920
Opened 2023-11-28 16:55 UTC by theproducer

Fixes an issue on iOS 17 where setting keyboard style would not apply the new appearance.

closes: https://github.com/ionic-team/capacitor-plugins/issues/1905

2023-11-28 16:58 UTC, markemer approved these changes

2023-11-29 17:35 UTC, jcesarmobile requested changes
This doesn't fix the reported issue.
The reported issue is when the keyboard is hidden, if you change the style, next time the keyboard appears it still has the old style on iOS 17 devices, and on the second time it appears it has the correct style.
So calling `[self changeKeyboardStyle:self.keyboardStyle];` on `onKeyboardWillHide` will have no effect since the keyboard is hidden and `onKeyboardWillHide` will not be called.

What seems to work is to call `[self changeKeyboardStyle:self.keyboardStyle];` inside the `- (void)setStyle:(CAPPluginCall *)call`.

2023-11-29 18:55 UTC, theproducer commented
> ...when the keyboard is **hidden**...

Ah right, sorry, I was tunnel visioned in to testing toggling open keyboards back and forth.

2023-11-30 15:30 UTC, jcesarmobile requested changes
This other call to the same method can be removed now
https://github.com/ionic-team/capacitor-plugins/blob/main/keyboard/ios/Sources/KeyboardPlugin/Keyboard.m#L124

2023-11-30 21:11 UTC, merged