docs(android): document plugin variables
ionic-team/capacitor-plugins pull request #204
Opened 2021-01-20 21:15 UTC by dwieeb

2021-01-21 11:01 UTC, jcesarmobile commented
I think it's ok to only put the ones specific for the plugin as the others are in capacitor/android and are included by default in `variables.gradle`

2021-01-21 19:46 UTC, dwieeb commented
Okay 👍 

I think we should document the capacitor/android variables somewhere, too 👉 https://github.com/ionic-team/capacitor-site/issues/208

2021-01-22 12:38 UTC, jcesarmobile requested changes
I think it should say the default version they use

2021-01-25 18:38 UTC, jcesarmobile approved these changes

2021-01-25 20:00 UTC, merged