chore: Update Package.swift for Cap6 release
ionic-team/capacitor-plugins pull request #2041
Opened 2024-02-27 19:05 UTC by markemer

2024-02-27 20:12 UTC, giralte-ionic approved these changes

2024-02-28 13:11 UTC, jcesarmobile requested changes
keyboard and status bar have incorrect names

2024-02-28 13:11 UTC, jcesarmobile commented on keyboard/Package.swift
> +            name: "CapacitorKeyboardPlugin",
```suggestion
            name: "CapacitorKeyboard",
```

2024-02-28 13:11 UTC, jcesarmobile commented on status-bar/Package.swift
> +            name: "CapacitorStatusBarPlugin",
```suggestion
            name: "CapacitorStatusBar",
```

2024-02-29 18:08 UTC, markemer commented
@jcesarmobile I got those two, I also changed the package name since that will also cause problems. Let me know if you find more - I think I got them all.

2024-03-01 18:15 UTC, theproducer approved these changes

2024-03-01 18:45 UTC, jcesarmobile approved these changes

2024-03-01 19:18 UTC, merged