Update readme as support for close on android was added in #1972
ionic-team/capacitor-plugins pull request #2197
Opened 2024-09-19 05:21 UTC by bentleyo

Support for browser close on android was added here:
https://github.com/ionic-team/capacitor-plugins/pull/1972

2024-09-20 13:43 UTC, jcesarmobile requested changes
as explained on https://github.com/ionic-team/capacitor-docs/pull/350, this is generated from the `definitions.ts` file, so should be updated there and then generate the `README.md` with `npm run build` command

2024-09-20 13:58 UTC, bentleyo commented
@jcesarmobile thanks for explaining, my apologies about that. I've updated the PR 😄

2024-09-20 14:21 UTC, jcesarmobile approved these changes

2024-09-20 14:41 UTC, bentleyo commented
@jcesarmobile is there any chance you could look over my other PR while you're active?
https://github.com/ionic-team/ionic-framework/pull/29877

It's a PR I created a few days ago about a bug in `ionic-framework`/`vue-router` that has been causing me some headaches. Hope it's not rude for me to ask, I'm happy to wait. Thanks again for your help!

2024-09-20 15:01 UTC, jcesarmobile commented
I have 0 Ionic experience, so no.

2025-02-12 13:55 UTC, menosprezzi commented
I think that this PR is good to be merged, no?
@jcesarmobile

2025-02-12 14:04 UTC, menosprezzi commented
+1

2025-07-03 12:29 UTC, closed without merging