fix(filesystem): Convert stat ctime/mtime timestamp to milliseconds
ionic-team/capacitor-plugins pull request #321
Opened 2021-03-18 21:12 UTC by theproducer

This PR makes `Filesystem.stat` return `ctime` and `mtime` in milliseconds iOS, bringing it in line with Android.

closes: https://github.com/ionic-team/capacitor-plugins/issues/313

2021-03-22 13:26 UTC, jcesarmobile requested changes
iOS is returning decimals, while Android and web aren't, so I think iOS shouldn't return the decimals neither.

The types should be updated to specify that it returns the value in milliseconds.

Android returns null for `ctime`, seems like it's possible to get the value on Android 26+, so we should probably return the value when available.

Should be documented on the upgrade guide since it can be considered a breaking change for iOS.

2021-03-23 11:41 UTC, jcesarmobile requested changes
Looks like the creation time code is not working, it returns the last modified value too.
So not sure if it's best to remove it again.

I've noticed that `lastAccessTime` seems to be the creation date, so maybe we can return the min between that and `creationTime` (just in case it's an android bug and they fix it in the future). That or remove the whole ctime return.
If we keep the ctime return, instead of 26 it's better to use `Build.VERSION_CODES.O`, and as there is already a `data.put("ctime", null);`, put that in the else of the android version check.

Also the README need to be re generated since the types changed.

2021-03-23 12:44 UTC, theproducer commented
Thanks - I'll open a PR in the docs for updates to the upgrade guide.

2021-03-23 12:49 UTC, jcesarmobile commented
Not sure if you saw my last comment since I requested changes and you requested review again without making any changes

2021-03-23 13:37 UTC, theproducer commented
Sorry, just saw them!

2021-03-23 19:00 UTC, jcesarmobile approved these changes
looks good

2021-03-24 13:02 UTC, merged