Share
ionic-team/capacitor-plugins pull request #39
Opened 2020-09-09 16:37 UTC by jcesarmobile

2020-09-15 23:46 UTC, dwieeb commented on share/rollup.config.js
> +    name: 'sharePlugin',
I think we're using this style in other plugins, but it's certainly up for discussion

```suggestion
    name: 'capacitorShare',
```

2020-09-16 16:53 UTC, dwieeb approved these changes

2020-09-17 16:03 UTC, carlpoole approved these changes

2020-09-18 20:00 UTC, ikeith requested changes

2020-09-21 15:50 UTC, ikeith approved these changes

2020-09-21 18:59 UTC, merged