Dialog
ionic-team/capacitor-plugins pull request #44
Opened 2020-09-17 17:46 UTC by jcesarmobile

2020-09-25 16:10 UTC, dwieeb commented
@adamdbradley Needs PWA element for web side

2020-09-25 16:35 UTC, carlpoole requested changes

2020-09-25 16:35 UTC, carlpoole commented on dialog/android/src/main/java/com/capacitorjs/plugins/dialog/DialogPlugin.java
> +        Dialog.alert(c, message, title, buttonTitle, (value, didCancel, inputValue) -> call.resolve());
rename `c` to `activity`, more descriptive

```suggestion
        final AppCompatActivity activity = this.getActivity();
        final String title = call.getString("title");
        final String message = call.getString("message");
        final String buttonTitle = call.getString("buttonTitle", "OK");

        if (title == null || message == null) {
            call.reject("Please provide a title or message for the alert");
            return;
        }

        if (activity.isFinishing()) {
            call.reject("App is finishing");
            return;
        }

        Dialog.alert(activity, message, title, buttonTitle, (value, didCancel, inputValue) -> call.resolve());
```

2020-09-25 16:35 UTC, carlpoole commented on dialog/android/src/main/java/com/capacitorjs/plugins/dialog/DialogPlugin.java
> +            c,
rename `c` to `activity`, more descriptive

```suggestion
        final AppCompatActivity activity = this.getActivity();
        final String title = call.getString("title");
        final String message = call.getString("message");
        final String okButtonTitle = call.getString("okButtonTitle", "OK");
        final String cancelButtonTitle = call.getString("cancelButtonTitle", "Cancel");

        if (title == null || message == null) {
            call.reject("Please provide a title or message for the alert");
            return;
        }

        if (activity.isFinishing()) {
            call.reject("App is finishing");
            return;
        }

        Dialog.confirm(
            activity,
```

2020-09-25 16:35 UTC, carlpoole commented on dialog/android/src/main/java/com/capacitorjs/plugins/dialog/DialogPlugin.java
> +            c,
rename `c` to `activity`, more descriptive

```suggestion
        final AppCompatActivity activity = this.getActivity();
        final String title = call.getString("title");
        final String message = call.getString("message");
        final String okButtonTitle = call.getString("okButtonTitle", "OK");
        final String cancelButtonTitle = call.getString("cancelButtonTitle", "Cancel");
        final String inputPlaceholder = call.getString("inputPlaceholder", "");
        final String inputText = call.getString("inputText", "");

        if (title == null || message == null) {
            call.reject("Please provide a title or message for the alert");
            return;
        }

        if (activity.isFinishing()) {
            call.reject("App is finishing");
            return;
        }

        Dialog.prompt(
            activity,
```

2020-09-25 16:35 UTC, carlpoole commented on dialog/android/src/main/java/com/capacitorjs/plugins/dialog/DialogPlugin.java
> +            c,
Minor thing. Looks good!

2020-09-25 17:12 UTC, dwieeb commented on dialog/src/definitions.ts
> +   * Title of de dialog.
```suggestion
   * Title of the dialog.
```

2020-09-25 17:12 UTC, dwieeb commented on dialog/src/definitions.ts
> +   * Title of de dialog.
```suggestion
   * Title of the dialog.
```

2020-09-25 17:12 UTC, dwieeb commented on dialog/src/definitions.ts
> +   * Title of de dialog.
```suggestion
   * Title of the dialog.
```

2020-09-25 18:58 UTC, ikeith approved these changes

2020-09-25 19:26 UTC, dwieeb approved these changes

2020-09-29 15:59 UTC, carlpoole approved these changes

2020-09-29 17:25 UTC, merged