fix: return promise in exitApp to allow catch in ios #750
ionic-team/capacitor-plugins pull request #777
Opened 2022-01-24 12:03 UTC by riderx

2022-01-24 17:04 UTC, jcesarmobile requested changes
Thanks for the PR

You also need to change `CAP_PLUGIN_METHOD(exitApp, CAPPluginReturnNone);` to `CAP_PLUGIN_METHOD(exitApp, CAPPluginReturnPromise);` in `AppPlugin.m` file.

We are not merging this yet as it's a breaking change and it's planned for when we start working in Capacitor 4 and version 2 of the plugins.

2022-01-24 18:53 UTC, riderx commented
@jcesarmobile thanks for the report. Do we have a doc somewhere do learn oh to code and test ?

2022-01-24 18:59 UTC, jcesarmobile commented
we test on the test-app, check its readme
https://github.com/ionic-team/capacitor-testapp#developing-capacitor

2022-01-24 19:02 UTC, riderx commented
My issue is more about installing package and using git with Lerna, i see 0 changes do i need a specific VSCode plugin ?

2022-01-24 22:54 UTC, jcesarmobile commented
If you run npm install on the root, lerna runs npm install on all plugins, same if you run npm run build, lerna runs it for all.
But you can also go to the plugin folder and run the same commands there, it will be faster as it will only run for that plugin instead of all.

2022-01-25 08:26 UTC, riderx commented
@jcesarmobile it seems from the doc i have to install Lerna in global right ? https://lerna.js.org/

2022-01-25 09:00 UTC, jcesarmobile commented
Not sure, it’s on the devDependencies, so shouldn’t be needed globally, but if it’s not working then you can give it a try.

2022-01-25 09:45 UTC, riderx commented
@jcesarmobile yes with Global install that do way different install flow ! Now i'm able to run all commands !

2022-01-25 15:39 UTC, riderx commented
@jcesarmobile i think that good in my side

2022-01-25 15:43 UTC, jcesarmobile commented on app/ios/Plugin/AppPlugin.m
> +           CAP_PLUGIN_METHOD(removeAllListeners, CAPPluginReturnPromise);
You have to change it in `exitApp`, not in `removeAllListeners`
```suggestion
           CAP_PLUGIN_METHOD(removeAllListeners, CAPPluginReturnNone);
```

2022-01-25 16:51 UTC, riderx commented
Sorry @jcesarmobile  i was sick yesterday :/ i updated

2022-02-22 04:10 UTC, riderx commented
@jcesarmobile good for you ?

2022-03-01 16:55 UTC, jcesarmobile approved these changes

2022-03-01 16:56 UTC, merged