docs(app-launcher): fix typo in example section
ionic-team/capacitor-plugins pull request #819
Opened 2022-02-11 20:06 UTC by jonz94

Because `alert()` only accept one argument, the second argument `value` will be ignored, and thus the `value` will not be shown on screen in the original example.

2022-02-15 09:13 UTC, jcesarmobile requested changes
Can you instead replace the alert with a console.log?
There is another issue open about not using alerts in examples

2022-02-15 13:01 UTC, jonz94 commented
> Can you instead replace the alert with a console.log? There is another issue open about not using alerts in examples

Sure! 

I also checked the example of other plugins, and replace the alert with console.log

2022-03-01 12:50 UTC, jcesarmobile approved these changes

2022-03-01 13:14 UTC, jcesarmobile commented
thanks!

2022-03-01 13:14 UTC, merged