feat: docs
ionic-team/capacitor-plugins pull request #916
Opened 2022-04-05 19:35 UTC by theproducer

2022-04-06 14:14 UTC, IT-MikeS approved these changes

2022-04-06 14:14 UTC, IT-MikeS commented
Needs a `fmt` run but looks good otherwise

2022-04-18 19:45 UTC, IT-MikeS approved these changes

2022-04-27 16:35 UTC, dallastjames requested changes

2022-04-28 17:54 UTC, ItsChaceD approved these changes

2022-04-28 18:45 UTC, merged