chore(google-maps): update Gradle
ionic-team/capacitor-plugins pull request #985
Opened 2022-05-17 14:20 UTC by IT-MikeS

2022-05-17 14:31 UTC, giralte-ionic approved these changes

2022-05-17 15:12 UTC, jcesarmobile approved these changes

2022-05-17 16:08 UTC, ItsChaceD approved these changes

2022-05-18 12:42 UTC, jcesarmobile requested changes
you need to apply this change to the e2e android app as it's required when targeting SDK 31+
https://github.com/ionic-team/capacitor/commit/79b4a3c56ce9704bc8f5b0b8ce6d5e60f86d4d2c

2022-05-18 16:18 UTC, jcesarmobile approved these changes

2022-05-18 16:19 UTC, merged